name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn clean install
      - name: Build Docker Image
        run: |
          docker build \
            --build-arg APP_NAME=$(cat src/main/resources/application.properties | grep spring.application.name= | cut -d'=' -f2) \
            --build-arg APP_VERSION=$(mvn --non-interactive org.apache.maven.plugins:maven-help-plugin:3.0.1:evaluate -Dexpression=project.version | cut -d'"' -f2) \
            -t "${APP_NAME}:${APP_VERSION}" .
      - name: Login to Docker Registry
        run: docker login -u elvinhndrwn16 -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push "${APP_NAME}:${APP_VERSION}"
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 202.10.41.5
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker image prune -f
            docker pull "${APP_NAME}:${APP_VERSION}"
            docker run -d --name my_app "${APP_NAME}:${APP_VERSION}"