name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package
      - name: Build the Docker image
        run: docker build -t my-image:$GITHUB_SHA .
      - name: Push the Docker image
        run: docker push my-image:$GITHUB_SHA

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to VPS
        uses: docker://alpine:latest
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          apk add openssh-client
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/key-github root@${{ env.VPS_IP }} 'docker pull my-image:$GITHUB_SHA && docker stop my-container && docker rm -f my-container && docker run -d --name my-container -p 8080:8080 my-image:$GITHUB_SHA'